name: 'Demande de fonctionnalité'
description: 'Proposer une nouvelle fonctionnalité ou amélioration'
title: '[FEATURE] '
labels: ['enhancement', 'status:triage']
body:
  - type: textarea
    id: use-case
    attributes:
      label: "Cas d'utilisation"
      placeholder: 'En tant que [rôle], je souhaite [action] afin de [bénéfice].'
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 'Solution proposée'
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: 'Bénéfice attendu'
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives envisagées'
